#!/usr/bin/env python3
"""Tests for lib/srcmap.py: synthetic generated files in both marker forms
SandPiper 1.14 emits (//_\\source with --noline, as fev.sh runs it, and `line
without), the "// For <sig>." fallback inside the inlined declarations, and
message annotation. Real generated files are checked too when present
(SRCMAP_REAL_DIR, a module dir holding wip.sv + wip.tlv, or the reference
states below); missing ones are skipped. No network, no MDIR.

Run: python3 srcmap_test.py
"""
import os
import re
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from lib import srcmap

TLV = """\
\\m5_TLV_version 1d: tl-x.org
\\m5
   use(m5-1.0)
\\TLV body(/_top)
   |default
      @0
         <<1$x[3:0] = $a + 1;
\\SV
module m(input clk, output [3:0] y);
\\TLV
   |default
      @0
         $a[3:0] = 4'd1;
   m5+body(/top)
   |default
      @0
         *y = $x;
\\SV
endmodule
"""

SOURCE_FORM = """\
//_\\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\\source wip.tlv 7
//_\\SV
module m(input clk, output [3:0] y);
// ---------- Generated Code Inlined Here (before 1st \\TLV) ----------
// For |default$x.
logic [3:0] DEFAULT_x_a0;
// For |default$a.
logic [3:0] DEFAULT_a_a0;
// ---------- Generated Code Ends ----------
//_\\TLV
   //_|default
      //_@0
         assign DEFAULT_a_a0[3:0] = 4'd1;
   //_\\source wip.tlv 4   // Instantiated from wip.tlv, 14 as: m5+body(/top)
      //_|default
         //_@0
            assign DEFAULT_x_a0[3:0] = DEFAULT_a_a0 + 1;
   //_\\end_source
   //_|default
      //_@0
         assign y = DEFAULT_x_a0;
//_\\SV
endmodule
"""

LINE_FORM = """\
`line 2 "wip.tlv" 0 //_\\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
`line 8 "wip.tlv" 1
//_\\SV
module m(input clk, output [3:0] y);
// ---------- Generated Code Inlined Here (before 1st \\TLV) ----------
`line 0 "wip.sv" 1
// For |default$x.
logic [3:0] DEFAULT_x_a0;
// ---------- Generated Code Ends ----------
`line 10 "wip.tlv" 2
//_\\TLV
   //_|default
      //_@0
         assign DEFAULT_a_a0[3:0] = 4'd1;
   `line 5 "wip.tlv" 1   // Instantiated from wip.tlv, 14 as: m5+body(/top)
      //_|default
         //_@0
            assign DEFAULT_x_a0[3:0] = DEFAULT_a_a0 + 1;
   //_\\end_source
   `line 15 "wip.tlv" 2
   //_|default
      //_@0
         assign y = DEFAULT_x_a0;
//_\\SV
endmodule
"""

# (sv line, expected tlv line, expected instantiation line) per form.
SOURCE_EXPECT = [(2, 7, None), (3, 8, None), (4, 9, None), (7, 7, None), (9, 13, None),
                 (11, 10, None), (14, 13, None), (16, 5, 14), (18, 7, 14), (20, 15, None),
                 (22, 17, None), (24, 19, None)]
SOURCE_NONE = [1, 5, 10, 19]
LINE_EXPECT = [(3, 8, None), (4, 9, None), (8, 7, None), (11, 10, None), (14, 13, None),
               (16, 5, 14), (18, 7, 14), (21, 15, None), (23, 17, None), (25, 19, None)]
LINE_NONE = [1, 2, 6, 10, 15, 19, 20]

CASES = []


def case(name):
    def deco(fn):
        CASES.append((name, fn))
        return fn
    return deco


def module_dir(sv_text):
    d = tempfile.mkdtemp(prefix="srcmap_")
    open(os.path.join(d, "wip.tlv"), "w").write(TLV)
    open(os.path.join(d, "wip.sv"), "w").write(sv_text)
    return d


def check_map(sv, expect, none):
    for n, tl, inst in expect:
        loc = srcmap.map_line(sv, n)
        assert loc is not None, f"sv:{n} unmapped, expected tlv:{tl}"
        assert (loc.line, loc.inst) == (tl, inst), f"sv:{n} -> {loc.line} inst {loc.inst}, expected {tl} inst {inst}"
        assert os.path.basename(loc.file) == "wip.tlv", loc.file
    for n in none:
        assert srcmap.map_line(sv, n) is None, f"sv:{n} mapped, expected None"


@case("\\source form: every code line maps, markers and banners do not")
def _():
    d = module_dir(SOURCE_FORM)
    check_map(os.path.join(d, "wip.sv"), SOURCE_EXPECT, SOURCE_NONE)


@case("`line form: every code line maps, directives and banners do not")
def _():
    d = module_dir(LINE_FORM)
    check_map(os.path.join(d, "wip.sv"), LINE_EXPECT, LINE_NONE)


@case("generated declaration maps through its // For comment to the assignment")
def _():
    d = module_dir(SOURCE_FORM)
    loc = srcmap.map_line(os.path.join(d, "wip.sv"), 7)
    assert loc.via == "|default$x" and loc.line == 7, loc
    assert "assignment of |default$x" in srcmap.describe(loc)


@case("out-of-range, missing file and marker-free file give None")
def _():
    d = module_dir(SOURCE_FORM)
    sv = os.path.join(d, "wip.sv")
    assert srcmap.map_line(sv, 0) is None and srcmap.map_line(sv, 999) is None
    assert srcmap.map_line(os.path.join(d, "nope.sv"), 1) is None
    open(os.path.join(d, "prepared.sv"), "w").write("module m;\nendmodule\n")
    assert srcmap.map_line(os.path.join(d, "prepared.sv"), 1) is None


@case("annotate: EQY reference gets the TLV tag and one quoted block")
def _():
    d = module_dir(SOURCE_FORM)
    msg = ("EQY [fev] read_gate: wip.sv:18: ERROR: syntax error\n"
           "EQY [fev] read_gate: wip.sv:18: ERROR: job failed\n")
    got = srcmap.annotate(msg, d)
    assert "wip.sv:18: ERROR: syntax error  [wip.sv:18 is from TLV wip.tlv:7 (macro body; instantiated at line 14)]\n" in got, got
    assert got.count("TLV source at wip.tlv:7:") == 1, got
    assert "\n    >    7:          <<1$x[3:0] = $a + 1;" in got, got
    assert "         6:       @0" in got and "         8: \\SV" in got, got
    assert got.count("is from TLV") == 2, got


@case("annotate: declaration error names the assignment; SandPiper TLV error is quoted")
def _():
    d = module_dir(SOURCE_FORM)
    got = srcmap.annotate("read_gold: wip.sv:7: ERROR: Non-constant range in declaration of \\DEFAULT_x_a0", d)
    assert "\\DEFAULT_x_a0  [wip.sv:7 is from TLV wip.tlv:7 (assignment of |default$x, whose generated declaration this is)]\n" in got, got
    got = srcmap.annotate("FATAL_ERROR(10) (BAD-SCOPE): File 'wip.tlv' Line 17 (char 3)\n\tScope not found.", d)
    assert "TLV source at wip.tlv:17:" in got and ">   17:          *y = $x;" in got, got
    assert got.startswith("FATAL_ERROR(10) (BAD-SCOPE): File 'wip.tlv' Line 17 (char 3)\n  TLV source"), got


@case("annotate: unmappable references and plain text are untouched")
def _():
    d = module_dir(SOURCE_FORM)
    open(os.path.join(d, "prepared.sv"), "w").write("module m;\nendmodule\n")
    for msg in ("prepared.sv:1: ERROR: x\n", "wip.sv:1: ERROR: header\n", "wip.sv:5: Warning: banner\n",
                "missing.sv:3: ERROR: y\n", "All FEV runs successful\n", "File 'other.tlv' Line 3\n"):
        assert srcmap.annotate(msg, d) == msg, (msg, srcmap.annotate(msg, d))


def real_check(sv, tlv):
    svl = open(sv).read().splitlines()
    tl = open(tlv).read().splitlines()
    form = "`line" if any(l.startswith("`line") for l in svl) else "\\source"
    hits = 0
    for i, l in enumerate(svl, 1):
        m = re.match(r"\s*assign (\w+?)_a0(?:\[[^\]]*\])? = (\w+);\s*$", l)
        if not m or "DEFAULT_" not in m.group(1) or m.group(2).startswith("DEFAULT_"):
            continue
        sig = m.group(1).split("DEFAULT_", 1)[1]
        loc = srcmap.map_line(sv, i)
        assert loc and loc.file == tlv, f"{sv}:{i} -> {loc}"
        want = f"${sig}"
        assert want in tl[loc.line - 1] and f"*{m.group(2)}" in tl[loc.line - 1], \
            f"{sv}:{i} {l.strip()!r} -> {tlv}:{loc.line} {tl[loc.line - 1].strip()!r}"
        hits += 1
    for i, l in enumerate(svl, 1):
        if l.startswith("// For ") and "$" in l:
            loc = srcmap.map_line(sv, i + 1)
            sig = l.strip().rstrip(".").rsplit("$", 1)[1]
            assert loc and re.search(r"\$\$?" + re.escape(sig) + r"\b", tl[loc.line - 1]), \
                f"{sv}:{i + 1} via {l.strip()!r} -> {loc}"
            hits += 1
            break
    assert hits >= 3, f"only {hits} checks in {sv}"
    return form, hits


REAL = [(os.environ.get("SRCMAP_REAL_DIR", ""), "wip"),
        (os.path.expanduser("~/projects/research/redwood-eda/serv/tlv/serv_rf_ram_if"), "feved"),
        (os.path.expanduser("~/projects/research/redwood-eda/serv/tlv/serv_aligner"), "feved")]

for d, stem in REAL:
    sv, tlv = os.path.join(d, stem + ".sv"), os.path.join(d, stem + ".tlv")
    if d and os.path.exists(sv) and os.path.exists(tlv):
        @case(f"real SandPiper output: {sv}")
        def _(sv=sv, tlv=tlv):
            form, hits = real_check(sv, tlv)
            print(f"      ({form} form, {hits} port-connection and declaration lines traced)")
    else:
        print(f"skip (not present): {sv or '$SRCMAP_REAL_DIR'}")

failed = 0
for name, fn in CASES:
    try:
        fn()
        print(f"  ok   {name}")
    except AssertionError as e:
        failed += 1
        print(f"  FAIL {name}\n       {e}")
print(f"{len(CASES) - failed}/{len(CASES)} cases passed")
sys.exit(1 if failed else 0)
